import ImgHero from './ImgHero.jpg';
import ImgArrival1 from './ImgArrival1.jpg';
import ImgArrival2 from './ImgArrival2.jpg';
import ImgArrival3 from './ImgArrival3.jpg';
import CategoryMen from './CategoryMan.jpg';
import CategoryWomen from './CategoryWomen.jpg';
import CategoryKids from './CategoryKids.jpg';
import Popular1 from './Popular1.jpg';
import Popular2 from './Popular2.jpg';
import Popular3 from './Popular3.jpg';
import Popular4 from './Popular4.jpg';
import Popular5 from './Popular5.jpg';
import Popular6 from './Popular6.jpg';
import ImgBlog from './ImgBlog.jpg';
import CatalogClothing from './CatalogClothing.jpg';
import CatalogShoes from './CatalogShoes.jpg';
import CatalogBags from './CatalogBags.jpg';
import WomanClothing from './WomanClothes.jpg';
import WomanShoes from './WomanShoes.jpg';
import WomanBags from './WomanBags.jpg';
import KidsClothing from './KidsClothes.jpg';
import KidsShoes from './KidsShoes.jpg';
import KidsBags from './KidsBags.jpg';
import Woman from './WomanClothes.jpg';
import Woman1 from './WomanClothes1.jpg';
import Woman2 from './WomanClothes2.jpg';
import Woman3 from './WomanClothes3.jpg';
import Woman4 from './WomanClothes4.jpg';
import Woman5 from './WomanClothes5.jpg';
import success from './success.jpg';
import { ReactComponent as IconTruck } from './icons/icTruck.svg';
import { ReactComponent as IconGift } from './icons/IcGift.svg';
import { ReactComponent as IconShoppingBag } from './icons/IcShopping-bag.svg';

export { ImgHero, ImgArrival1, ImgArrival2, ImgArrival3, CategoryMen, CategoryWomen, CategoryKids, ImgBlog, Popular1, Popular2, Popular3, Popular4, Popular5, Popular6, IconTruck, IconGift, IconShoppingBag, CatalogBags, CatalogShoes, CatalogClothing, WomanBags, WomanShoes, WomanClothing, KidsClothing, KidsShoes, KidsBags, Woman, Woman1, Woman2, Woman3, Woman4, Woman5, success }